---
title: "Lab7"
author: "Ethan Rutledge"
date: "10/27/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# X the 2-dimensional data, usually a data frame or a matrix
# MARGIN whether to apply the function to rows (MARGIN = 1) 
# or columns (MARGIN = 2)
# FUN The function to apply to the rows or columns


# Create simulated data
dat = matrix(1:49, nrow = 7, ncol = 7)

# Minimum and maximum values in each row

apply(dat, MARGIN = 1, FUN = min)

apply(dat, MARGIN = 1, FUN = max)

# Mean values in each column

apply(dat, MARGIN = 2, FUN = mean)

```

```{r}
moths = read.csv(here("data", "moths.csv"))
head(moths)

```

```{r}
# numeric() creates an vector of length m with all values initialized to zero
result = numeric(m)
head(result)

```

```{r}
# Perform the bootstrap
for(i in 1:m)
{
  result[i] = mean(sample(moths$anst, replace=TRUE))
}

```

```{r}
# The vector result now contains 10,000 bootstrap sample means. We can calculate the mean of the bootstrap means and, more importantly, the 2.5% and 97.5% quantiles of the bootstrap distribution, as follows:

mean(result)

quantile(result,c(0.025,0.975))
```

```{r}
install.packages("boot")

require(boot)

boot(data, statistic, R)

```

```{r}
#We want to calculate to mean, but we know that mean() can sometimes have trouble with NA values.

#To use it with boot() we have to create a modified version of the mean() function that automatically excludes NAs:

boot_mean = function(x, i)
{
  return(mean(x[i], na.rm = TRUE))
}

```

```{r}

# Now we can find the bootstrap for 10000 iterations:

myboot = 
  boot(
    data = moths$anst,
    statistic = boot_mean,
    R = 10000)
print(myboot)

```


















