---
title: "Inclass_Likelihood"
author: "Ethan Rutledge"
date: "10/21/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
dat_bird = read.csv(here::here("data", "bird.sta.csv"))
dat_habitat = read.csv(here::here("data", "hab.sta.csv"))
dat_all = merge(dat_bird, dat_habitat)

```

```{r}
hist(dat_all$WIWA, breaks = 0:7 - .5)

```

```{r}
par(mfrow = c(1, 2))
dat = dat_all$WIWA
hist(dat, breaks = 0:(max(dat) + 1) - 0.5, main = "Histogram of\nWilson's Warbler counts")

dat = dat_all$GRJA
hist(dat, breaks = 0:(max(dat) + 1) - 0.5, main = "Histogram of\nGray Jay counts")
```

```{r}
sum(log(dpois(x = dat_all$WIWA, lambda = 1.7)))
```

Find the lamda that maximizes the likelihood
Just use the mean of 2 and 6 which is 4
```{r}
wiwa_counts = c(2, 6)
sum(log(dpois(x = wiwa_counts, lambda = 4)))

```

```{r}
dat = dat_all$WIWR
hist(dat, breaks = 0:(max(dat) + 1) - 0.5, main = "Histogram of\nWinter Wren counts")

```
Find the lamda that maximizes the likelihood
Just use the mean of dat_all$WIWR which is 1.456
```{r}
sum(log(dpois(x = dat_all$WIWR, lambda = 1.456)))

```

```{r}
sum(log(dbinom(dat_all$WIWR , 38, 0.038)))

```

